app:
  swagger-context-path: /dev/example
#  swagger-context-path: ""

micronaut:
  application:
    name: micronaut-openapi-context-path-issue
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /docs/swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /docs/swagger-ui/**
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /docs/swagger-ui-res/**
  server:
    port: 8080